version: '3.8'

services:
  mssvn_web_app:
    container_name: mssvn_web_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: ${VITE_API_URL}
    env_file:
      - .env
    ports:
      - "3000:80"
    networks:
      - mssvn_backend

networks:
  mssvn_backend:
    name: mssvn_backend
    external: true
